### PR TITLE
fix: add CTF Exchange approval to approvals example

### LINKED ISSUE #35: Examples/approvals.rs | There is no CTF Exchange approval?
Was working on bridging my wallet to the CLOB, but couldn't since there were no funds in the CTF Exchange for markets??

```
let standard_exchange: Address = address!("0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E");
approve(&token, standard_exchange, U256::MAX).await?;
set_approval_for_all(&ctf, standard_exchange, true).await?;
```

please include this in the examples if possible

### PR DESCRIPTION
**Pull request by Haut**
Closes #35

The `examples/approvals.rs` was approving the **wrong contract**, causing users to be unable to trade on standard (non-neg-risk) markets.

**The bug (lines 54-55 in old code):**
```rust
approve(&token, config.conditional_tokens, U256::MAX).await?;
set_approval_for_all(&ctf, config.conditional_tokens, true).await?;
```

This approved `conditional_tokens` (`0x4D97DCd9...`) instead of `exchange` (`0x4bFb41d5...`).

## Verified On-Chain

Tested on Polygon mainnet:

**After running OLD code (main branch):**
```
CTF Exchange (0x4bFb41d5...):
  USDC allowance: 0 ❌
  CTF approved:   false ❌

Neg Risk CTF Exchange: ✅
Neg Risk Adapter: ✅
```

**After running NEW code (this PR):**
```
CTF Exchange (0x4bFb41d5...):
  USDC allowance: MAX (unlimited) ✅
  CTF approved:   true ✅

Neg Risk CTF Exchange: ✅
Neg Risk Adapter: ✅
```

## Changes

**`src/lib.rs`:**
- Added `neg_risk_adapter: Option<Address>` field to `ContractConfig`
- Standard configs: `None`
- Neg-risk configs: `Some(0xd91E80cF2E7be2e162c6513ceD06f1dD0dA35296)`

**`examples/approvals.rs`:**
- Fixed bug: now approves `config.exchange` (CTF Exchange) instead of `config.conditional_tokens`
- Uses `neg_risk_config.neg_risk_adapter` field properly (previously pulled from AMOY testnet config)
- Added allowance query functions to verify before/after state
- Added documentation explaining the three required contracts

**`examples/check_approvals.rs` (new):**
- Read-only example to check current approvals for any wallet
- No private key or gas required
- Usage: `cargo run --example check_approvals -- <ADDRESS>`

## Required Approvals

| Contract | Address | Purpose |
|----------|---------|---------|
| CTF Exchange | `0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E` | Standard market trading |
| Neg Risk CTF Exchange | `0xC5d563A36AE78145C45a50134d48A1215220f80a` | Neg-risk market trading |
| Neg Risk Adapter | `0xd91E80cF2E7be2e162c6513ceD06f1dD0dA35296` | Token minting/splitting |

Addresses verified against [py-clob-client](https://github.com/Polymarket/py-clob-client) and [neg-risk-ctf-adapter](https://github.com/Polymarket/neg-risk-ctf-adapter/blob/main/addresses.json).

### CODE REVIEW

File: examples/approvals_dry_run.rs
Comment (chaz-polymarket) [inline examples/approvals_dry_run.rs:1]: any chance you can combine the dry run with `approvals` instead of having a separate example

File: examples/compare_approvals.rs
Comment (chaz-polymarket) [inline examples/compare_approvals.rs:1]: please remove this isn't needed

File: examples/approvals.rs [hunk 1]
```diff
@@ -22,57 +48,137 @@ sol! {
...
+    Ok(approved)
+}
+
 async fn approve<P: alloy::providers::Provider>(
     usdc: &IERC20::IERC20Instance<P>,
     spender: Address,
     amount: U256,
 ) -> Result<()> {
-    println!("Calling USDC.approve({spender:?}, {amount})...");
+    println!("  Calling USDC.approve({spender:?}, max)...");
```
Comment (chaz-polymarket) [inline examples/approvals.rs]: this should be `amount` still

**Review by mshrieve — DISMISSED** [review]
